;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; GLOBAL KEY MAPPINGS
(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key "\C-xm"    'execute-extended-command)
(global-set-key "\C-c\C-m" 'execute-extended-command)
(global-set-key "\C-w"     'backward-kill-word)
(global-set-key "\C-x\C-k" 'kill-region)
(global-set-key "\C-c\C-k" 'kill-region)
(global-set-key "\C-c\C-y" 'transpose-chars)
(global-set-key "\C-t"     'dabbrev-expand)
(global-set-key "\C-z"     'advertised-undo)
(global-set-key "\C-ch"   'help-command)
(global-set-key "\C-h"     'delete-backward-char)
(global-set-key "\M-s"     'isearch-forward-regexp)
(global-set-key "\M-g"     'goto-line)
(global-set-key "\C-xt"    'toggle-truncate-lines)
(global-set-key "\C-xa"    'find-file-at-point)
(global-set-key "\M-p"     'scroll-down-one)
(global-set-key "\M-n"     'scroll-up-one)
(global-set-key "\C-xp"    'shell)
(global-set-key "\C-x\C-p" 'rename-buffer)
(global-set-key "\C-x\C-b" 'sw-list)
(global-set-key [f8]       'sw-list)
(global-set-key "\C-ca"    'restart-apache)
(global-set-key "\C-cp"    'new-shell)

(fset 'scroll-up-one   "\C-u1\C-v")
(fset 'scroll-down-one "\C-u1\M-v")
